PIDs:
  X:
    kp:  17.0 #5.0 #0.05 #5.0
    kd:  70.0 #25.0 #5.0
    ki:  90.0 #50.0  #50.0
    minOutput: -50.0
    maxOutput: 50.0
    integratorMin: -0.1
    integratorMax: 0.1
  Y:
    kp: -17.0  #-5.0 #-5.0
    kd: -70.0  #-25.0 #-5.0
    ki: -90.0  #-50.0 #-50.0
    minOutput: -50.0
    maxOutput: 50.0
    integratorMin: -0.1
    integratorMax: 0.1
  Z:
    kp:  15.0 #4000.0  #4000.0
    kd:  18.0 #5000.0  #5000.0
    ki:   2.5 #3500.0  #3500.0
    minOutput: 10000.0
    maxOutput: 60000.0
    integratorMin: -1000.0
    integratorMax: 1000.0
  Yaw:
    kp: -200.0
    kd: -20.0
    ki: 0.0
    minOutput: -200.0
    maxOutput: 200.0
    integratorMin: 0.0
    integratorMax: 0.0
